### ISSUE TITLE
Add a way to view/show cluster level information

### ISSUE THREAD

**Issue by cb-davidelliott** [couchbaselabs/VSCode-Couchbase#169]
I'd like a way to view certain cluster info while I'm using the tool and get additional cluster information via a "get info" button. 

- Next to the cluster name, put the logged in user and the database name, next to the connection name
  - so I can see at a glance what I'm connected to regardless of what I may have named the connection
 
- Add an option similar to the "Get Info" for the bucket that shows the following so I can easily get to that information
  - Cluster hostname
  - Database name
  - Logged in Username
  - Date/Time the cluster was refreshed
  - Server version
  - Nodes and services
  - Provider
  - Project
  - Server Version

**Comment by deniswsrosa** [comment]
couple questions:

- What database name means? because we already list all buckets
- Date/Time the cluster was refreshed - not sure what you mean by "refreshed"- We are loading things on the fly there
- Provider - unclear what you mean here.
- Project -  do you mean Capella Project? Could you please elaborate why would you need that?
