### ISSUE TITLE
command 'vscode-couchbase.createClusterConnection' not found

### ISSUE THREAD

**Issue by brianking** [couchbaselabs/VSCode-Couchbase#174]
When trying to create a connection, I get the error:

command 'vscode-couchbase.createClusterConnection' not found

I have openssl installed and restarted VS Code multiple time.
brianking@lmemea1943 ~ % which openssl
/usr/bin/openssl

OS: macOS M1 chip

**Comment by AayushTyagi1** [comment]
Likely, the problem is only related to openssl. 
To troubleshoot, please use the shortcut Cmd + P and search for "Developer: Toggle Developer Tools" and select it. This will allow you to access the developer tools, where you can see the actual issue with the installation. 
It is highly possible that the problem is related to openssl and this should be reflected in the developer tools.

**Comment by AayushTyagi1** [comment]
The developer tools are built into the editor itself. You can access them by opening the Command Palette (Ctrl+Shift+P on Windows or Command+Shift+P on Mac) and searching for "Toggle Developer Tools". 
Below is the screenshot attached for reference
<img width="1728" alt="Screenshot 2023-04-10 at 4 05 31 PM" src="https://user-images.githubusercontent.com/42893909/230885866-942fa2be-8ed7-4608-854a-f9c4a8278d64.png">
